import re

# Keywords to category mapping for rule-based fallback
keyword_to_category = {
    r'\bIKEA\b': ('Housing', 'Building & Garden'),
    r'\bMAX\b': ('Food & Drink', 'Restaurant & Bar'),
    r'\bICA\b': ('Food & Drink', 'Groceries'),
    r'\bNetflix\b': ('Household', 'Media, Mobile, and IT'),
    r'\bSpotify\b': ('Household', 'Media, Mobile, and IT'),
    r'\bDin Veterinär\b': ('Household', 'Pets'),
    r'\bMicrosoft\b': ('Household', 'Media, Mobile, and IT'),
    r'\bSTUDSTÖD\b': ('Miscellaneous', 'Support & Subsidies'),
    r'\bWh\b': ('Food & Drink', 'Groceries'),
    r'\bCIRCLE K\b': ('Transport', 'Vehicles & Fuel'),
    r'\bFrukt\b': ('Food & Drink', 'Groceries'),
    r'\bAPOTEK\b': ('Household', 'Healthcare & Wellness'),
    r'\bLEJONET\b': ('Food & Drink', 'Café & Snacks'),
    r'\bG2A.COM\b': ('Entertainment & Shopping', 'Toys & Games'),
    r'\bGOOGLE\b': ('Household', 'Media, Mobile, and IT'),
    r'\bLiseberg\b': ('Entertainment & Shopping', 'Culture & Entertainment'),
    r'\bVästtrafik\b': ('Transport', 'Bus & Train'),
    r'\bAVANZA\b': ('Miscellaneous', 'Savings'),
    r'\bHORNBACH\b': ('Housing', 'Building & Garden'),
    r'\bTelia\b': ('Household', 'Media, Mobile, and IT'),
    r'\bDisney Plus\b': ('Household', 'Media, Mobile, and IT'),
    r'\bCafé\b': ('Food & Drink', 'Café & Snacks'),
    r'\bJOHN SCOTTS\b': ('Food & Drink', 'Restaurant & Bar'),
    r'\bWillys\b': ('Food & Drink', 'Groceries'),
    r'\bSJ\b': ('Transport', 'Bus & Train'),
    r'\bSystembolaget\b': ('Food & Drink', 'Alcohol & Tobacco'),
    r'\bBlizzard\b': ('Entertainment & Shopping', 'Toys & Games'),
    r'\bApoteket\b': ('Household', 'Healthcare & Wellness'),
    r'\bAmazon Prime\b': ('Household', 'Media, Mobile, and IT'),
    r'\bCapitol\b': ('Entertainment & Shopping', 'Culture & Entertainment'),
    r'\bZettle\b': ('Food & Drink', 'Café & Snacks'),
    r'\b7-Eleven\b': ('Food & Drink', 'Café & Snacks'),
    r'\bLuxury Sushi\b': ('Food & Drink', 'Restaurant & Bar'),
    r'\bPizzabageriet\b': ('Food & Drink', 'Restaurant & Bar'),
    r'\bTorps Cafe\b': ('Food & Drink', 'Café & Snacks'),
    r'\bElgiganten\b': ('Entertainment & Shopping', 'Home Electronics'),
    r'\bPreem\b': ('Transport', 'Vehicles & Fuel'),
    r'\bSushi Yama\b': ('Food & Drink', 'Restaurant & Bar'),
    r'\bCity Gross\b': ('Food & Drink', 'Groceries'),
    r'\bSwish\b': ('Miscellaneous', 'Swish'),
    r'\bBauhaus\b': ('Housing', 'Building & Garden'),
    r'\bClas Ohlson\b': ('Household', 'Electronics'),
    r'\bShell\b': ('Transport', 'Vehicles & Fuel'),
    r'\bMAX Burgers\b': ('Food & Drink', 'Restaurant & Bar'),
    r'\bVR Sverige\b': ('Entertainment & Shopping', 'Electronics'),
    r'\bNetOnNet\b': ('Household', 'Electronics'),
    r'\bWayne\'s Coffee\b': ('Food & Drink', 'Café & Snacks'),
    r'\bVeterinärkliniken\b': ('Household', 'Pets'),
    r'\bToys"R"Us\b': ('Entertainment & Shopping', 'Toys & Games'),
    r'\bScandic Hotels\b': ('Entertainment & Shopping', 'Vacation'),
    r'\bCoop\b': ('Food & Drink', 'Groceries'),
    r'\bEspresso House\b': ('Food & Drink', 'Café & Snacks'),
    r'\bAlko\b': ('Food & Drink', 'Alcohol & Tobacco'),
    r'\bDjurmagazinet\b': ('Household', 'Pets'),
    r'\bRadisson Blu\b': ('Entertainment & Shopping', 'Vacation'),
    r'\bBurger King\b': ('Food & Drink', 'Restaurant & Bar'),
    r'\bSt1\b': ('Transport', 'Vehicles & Fuel'),
    r'\bKICKS\b': ('Entertainment & Shopping', 'Beauty & Personal Care'),
    r'\bStadium\b': ('Entertainment & Shopping', 'Sports & Leisure'),
    r'\bStarbucks\b': ('Food & Drink', 'Café & Snacks'),
    r'\bDjuraffär\b': ('Household', 'Pets'),
    r'\bCircle K\b': ('Transport', 'Vehicles & Fuel'),
    r'\bElectrolux\b': ('Entertainment & Shopping', 'Home Electronics'),
    r'\bHoliday Inn\b': ('Entertainment & Shopping', 'Vacation'),
    r'\bDecathlon\b': ('Entertainment & Shopping', 'Sports & Leisure'),
    r'\bCinema City\b': ('Entertainment & Shopping', 'Culture & Entertainment'),
    r'\bAdidas Store\b': ('Entertainment & Shopping', 'Sports & Leisure'),
    r'\bArken Zoo\b': ('Household', 'Pets'),
    r'\bHM\b': ('Entertainment & Shopping', 'Clothes & Fashion'),
    r'\bFilmstaden\b': ('Entertainment & Shopping', 'Culture & Entertainment')
}

def rule_based_categorization(text):
    for pattern, (category, subcategory) in keyword_to_category.items():
        if re.search(pattern, text, re.IGNORECASE):
            return category, subcategory
    return 'Uncategorized', 'Uncategorized'
