# Generated by Django 5.0.6 on 2024-06-18 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_remove_transaction_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Savings'), (2, 'Current'), (3, 'Investment'), (4, 'Other')], default=2)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Salary'), (2, 'Gift'), (3, 'Other')], default=3)),
                ('description', models.TextField(blank=True, default='')),
                ('repetitive', models.BooleanField(default=False)),
                ('repetition_interval', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly'), (5, 'None')], default=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Food'), (2, 'Transport'), (3, 'Rent'), (4, 'Bills'), (5, 'Health'), (6, 'Fun'), (7, 'Charity'), (8, 'Other')], default=8)),
                ('description', models.TextField(blank=True, default='')),
                ('repetitive', models.BooleanField(default=False)),
                ('repetition_interval', models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Yearly'), (5, 'None')], default=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
