# Generated by Django 5.0.6 on 2024-06-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0010_remove_income_author_remove_outcome_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
