# Generated by Django 5.0.6 on 2024-06-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0011_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurring_interval',
            field=models.TextField(default='', max_length=20),
        ),
    ]
