# Generated by Django 4.2.13 on 2024-07-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0012_alter_transaction_recurring_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subCategory',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
