# Generated by Django 4.2.13 on 2024-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0013_transaction_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subCategory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
