# Generated by Django 4.2.13 on 2024-07-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0014_alter_transaction_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurring_interval',
        ),
    ]
