# Generated by Django 4.2.14 on 2024-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0015_remove_transaction_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subCategory',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
